### ISSUE TITLE
deprecate functions to be removed

### ISSUE THREAD

**Issue by katexochen** [google/go-sev-guest#100]
[Last release ](https://github.com/google/go-sev-guest/releases/tag/v0.10.0) announced upcoming removal of a set of functions from this module. However, those functions are not marked as deprecated in a way that common Go tooling can detect it.

from https://go.dev/blog/godoc:
> To signal that an identifier should not be used, add a paragraph to its doc comment that begins with "Deprecated:" followed by some information about the deprecation.

**Comment by deeglaze** [comment]
Thanks for the report!
