### ISSUE TITLE
New GetRawQuote API fails if hypervisor does not call SNP_SET_EXT_CONFIG 

### ISSUE THREAD

**Issue by malt3** [google/go-sev-guest#102]
Getting the extended report requires the hypervisor to call `SNP_SET_EXT_CONFIG` with the cert chain, before the [corresponding ioctl](https://github.com/google/go-sev-guest/blob/f912a0a5e11e9aeb1ab8a3ceb617d8a135901a8b/client/client.go#L149) can succeed.

If the hypervisor never does so (which is optional) the new `GetRawQuote` API is unusable, even if a report without cert chain is needed, since the request to get the extended report will fail.

In particular, the following error is returned when the certificate cannot be provided: `error querying certificate length: unexpected firmware status (see SEV API spec): 6`.
Maybe go-sev-guest can detect this error ([INVALID_CERTIFICATE](https://github.com/google/go-sev-guest/blob/f912a0a5e11e9aeb1ab8a3ceb617d8a135901a8b/abi/amdsp.go#L38)) and fall back to a code path without certificate chain?

**Comment by deeglaze** [comment]
Thanks for the report! Does PR#104 work for you?

**Comment by malt3** [comment]
This does work as expected.

**Comment by malt3** [comment]
Fixed by #104
