### ISSUE TITLE
Can't fetch ASK and ARK on AWS SEV SNP vms

### ISSUE THREAD

**Issue by jianlinjiang** [google/go-sev-guest#134]
hi all, Thank you for providing this library!
I am testing this library on AWS SEV SNP vms. When I used this library to get a report on the AWS SEV SNP vm, I got these warnings. 

Can you please clarify why there are these warnings? Why doesn't the same code produce them on a Google confidential vm?
Thanks!
```
WARN : 2024/09/29 08:02:10.648414 abi.go:881: ASK certificate not found in data pages
WARN : 2024/09/29 08:02:10.649354 abi.go:884: ARK certificate not found in data pages
```
My sample code
```go
import (
	"crypto/ecdsa"
	"crypto/rand"
	"crypto/x509"
	"encoding/base64"
	"encoding/hex"
	"fmt"
	"io"

	sg "github.com/google/go-sev-guest/client"
	"github.com/google/go-tpm-tools/client"
	"github.com/google/go-tpm/legacy/tpm2"
)
func GetExtendedReport() {
	device, err := client.CreateSevSnpDevice()
	if err != nil {
		panic(err)
	}
	nonce := make([]byte, 64)
	_, err = io.ReadFull(rand.Reader, nonce)
	if err != nil {
		fmt.Println("Error:", err)
		return
	}
	extReport, err := sg.GetExtendedReport(device.Device, [64]byte(nonce))
	if err != nil {
		panic(err)
	}
	fmt.Printf("%v", extReport)
}

```

**Comment by deeglaze** [comment]
The certificate info is provided by the VMM operator, and AWS expects users to already add the ASVK (maybe just ASK, I haven’t messed with vlek much. It’s mostly only an AWS thing) and ARK to their own trust anchors. The VLEK in the buffer is all that AWS provides, and it should be sufficient. It’s the same cert on all AWS machines provided they’re using the same TCB.

**Comment by deeglaze** [comment]
These warnings probably just ought to be removed.
