### ISSUE TITLE
Dependency glog leaks go routine

### ISSUE THREAD

**Issue by 3u13r** [google/go-sev-guest#23]
Using go-tpm-tools/client introduces go-sev-guest/abi as dependency. This in turn depends on glog which leaks as shown below. Sadly, glog is [also unmaintained](https://github.com/golang/glog/pull/54#issuecomment-1035616115), so there's no way for us to provide a fix. Is it possible to replace glog with klog? The interface seems to be similar.

```
goleak: Errors on successful test run: found unexpected goroutines:
[Goroutine 19 in state chan receive, with github.com/golang/glog.(*loggingT).flushDaemon on top of the stack:
goroutine 19 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x0?)
	/home/euler/go/pkg/mod/github.com/golang/glog@v1.0.0/glog.go:882 +0x6a
created by github.com/golang/glog.init.0
	/home/euler/go/pkg/mod/github.com/golang/glog@v1.0.0/glog.go:410 +0x1bf
```

**Comment by deeglaze** [comment]
Thanks for your report. Will change to klog.
