### ISSUE TITLE
Build fails on GOARCH=386

### ISSUE THREAD

**Issue by MagicalTux** [google/go-sev-guest#62]
For some reason, `github.com/google/go-tpm-tools` depends on this package and causes build to fail on 32bits architectures:

../../go/pkg/mod/github.com/google/go-sev-guest@v0.6.1/abi/amdsp.go:105:53: cannot use 0x100000000 (untyped int constant 4294967296) as SevFirmwareStatus value in constant declaration (overflows)

This is blocking the whole build and is a bit problematic.

A way to fix this is to modify https://github.com/google/go-sev-guest/blob/main/abi/amdsp.go#L21C1-L21C27 

`type SevFirmwareStatus int`

To

`type SevFirmwareStatus int64`

I tested with `GOARCH=386 go build ./...` and confirmed there are no other issues preventing building this repository.

**Comment by deeglaze** [comment]
Thanks for your report. We'll get it fixed and cut a new release for go-tpm-tools to update to.
