### ISSUE TITLE
Limited Product Support

### ISSUE THREAD

**Issue by larrydewey** [google/go-sev-guest#64]
https://github.com/google/go-sev-guest/blob/14ac50e9ffcc05cd1d12247b710c65093beedb58/verify/verify.go#L49-L51

It would be good to update this to include subsequent hardware models.

**Comment by deeglaze** [comment]
Agreed, though I'd like to get my hands on a Genoa machine to test it in practice. Specifically, I'm not sure which VCEK productName values to expect, since the KDS spec only gives Milan-B0 as an example, and I don't have a Genoa CHIP_ID to check the returned value for its VCEK cert.

**Comment by deeglaze** [comment]
I've uploaded PR#65 if you'd like to review.
