### ISSUE TITLE
Improve error when fetching certificates

### ISSUE THREAD

**Issue by datosh** [google/go-sev-guest#69]
Hey :wave: 

I was trying to use 0.7.0 in order to verify an SNP attestation report on AWS. I know now that VLEK is used instead of VCEK and found https://github.com/google/go-sev-guest/pull/67. I will comment there as well once I played around with it :) 

While using 0.7.0 I got a somewhat confusing error. The error I got was `timeout` while downloading the VCEK. So I wasted quite a bit of time debugging (non existing network issues). What was actually happening is that the library was trying to fetch `https://kdsintf.amd.com/vcek/v1/Milan/00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000?blSPL=3&teeSPL=0&snpSPL=10&ucodeSPL=207` and AMD correctly responded with 404. [Currently everything >300 is handled the same](https://github.com/google/go-sev-guest/blob/main/verify/trust/trust.go#L105). I think we could narrow down the status code a bit and / or inform users about the underlying error while retrying. 

AMD seems to honor the status codes documented in [Chapter 4.1](https://www.amd.com/system/files/TechDocs/57230.pdf). So we could test for HTTP 429 and error early otherwise?

Let me know what you think. I am open to put in a PR as well.

**Comment by deeglaze** [comment]
Sounds good to me. Happy to review.
