### ISSUE TITLE
A small suggestion about compatibility

### ISSUE THREAD

**Issue by Laisky** [google/go-sev-guest#80]
https://github.com/google/go-sev-guest/commit/bee858aa162bad4cacd6d925859e8a2e74c67f76#diff-11eac54c87d256754b194b9fc9f84436b29b78da33c6104ba962067db5199d0eL174-L176

I think it is better not to arbitrarily change function signatures, especially within a minor version change, such as this breaking change occurring from `v0.7.0` to `v0.7.1`. It is better to annotate the change with a comment like `Deprecated: use xxx instead`, so that other developers can understand how to modify their code after upgrading.

Thanks

**Comment by deeglaze** [comment]
Thanks for that reminder. I usually do this when I know my users, and then migrate the callsites myself to complete the deprecation. How would you like to be informed of deprecations? Is pointing them out in release announcements enough?

**Comment by Laisky** [comment]
> Thanks for that reminder. I usually do this when I know my users, and then migrate the callsites myself to complete the deprecation. How would you like to be informed of deprecations? Is pointing them out in release announcements enough?

Considering that it is still a v0 version, any type of announcement would be appreciated😁
