### ISSUE TITLE
Is there a plan to support the legacy SEV report handling?

### ISSUE THREAD

**Issue by cowbon** [google/go-sev-guest#90]
Hi there,

In addition to SEV-SNP, the legacy SEV also produces a guest report, even though it's coming from the hypervisor. The report from the legacy SEV can be obtained from `ATTESTATION` ioctl from the hypervisor, and it contains a signature from PEK. Is there a plan to support the `validate` and `verify` for the legacy SEV report in this project?

**Comment by deeglaze** [comment]
No, legacy attestation is out of scope.
