### ISSUE TITLE
warning/error when using embedded AMD root of trust

### ISSUE THREAD

**Issue by katexochen** [google/go-sev-guest#97]
Hey, there is this warning that is a bit annoying when using the embedded AMD root cert:

```
ERROR: Logging before logger.Init.
WARN : 2024/01/08 11:42:54.739159 verify.go:501: Using embedded AMD certificates for SEV-SNP attestation root of trust
```

Actually, I think it is perfectly fine to use the certificate that is embedded in this library, and I don't expect the lib to throw a warning (and error) about something that is perfectly fine.

If you think the internal certificate shouldn't be used, I'd suggest to remove it completely and require callers to pass the certificate where needed.

**Comment by deeglaze** [comment]
I agree it's a nuisance. Thanks for your report. Will include in the next release when we incorporate configfs-tsm support.

**Comment by katexochen** [comment]
Thanks for the fast reaction and great work!
